### ISSUE TITLE
RYS01: Eu como usuário gostaria de poder me cadastrar na plataforma para poder criar contas

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#1]
- Deve existir na plataforma um formulário de cadastro
- Os meios de acesso a esse formulário devem ser: pelo botão “Cadastre-se” na página inicial da plataforma quando o usuário está deslogado, pela tela de login do usuário (opção “Não é cadastrado? Cadastre-se!” ou algo do gênero) e quando o usuário estiver deslogado e clicar para adicionar um jogo ao carrinho (no caso deve dar as duas opções: login ou cadastro)
- O formulário de cadastro deve possuir uma opção “Já é cadastrado? Faça seu login” que leva para a página de login
- Deve ser possível fechar o formulário de cadastro e voltar para a tela inicial da plataforma
- O formulário de cadastro deve solicitar: Nome de usuário* (deve haver verificação se o nome de usuário já foi cadastrado antes no banco de dados, caso sim, mensagem de erro informando. O front deve limitar tamanho do nome de usuário a 20 caracteres pois existirá essa limitação no banco), email* (também deve ser verificado no banco. O front deve verificar se o email está no formato correto), senha* (colocar campo para confirmar senha e verificar se as senhas são iguais), nome do perfil, CPF* (o backend deve verificar se o CPF é válido e se o mesmo já não está cadastrado no banco. Isso pode ser feito com funções prontas que se encontram na internet. O frontend deve possuir uma máscara que deixa o cpf no formato bonitinho xxx.xxx.xxx-xx, mas no banco, devem ser salvos apenas os valores numéricos), Celular (adicionar máscara no front para ficar no formato (xx) x xxxx-xxxx), sexo (deve ser um dropdown com as opções “Masculino”, “Feminino”, “Prefiro não informar”. No banco será do tipo char e aceitará os valores "F", "M", null)
- No banco, os dados da conta devem ser salvos na tabela de usuários, exceto o “nome do perfil” que deve ser salvo na tabela de perfis (que vai representar as diferentes contas de um mesmo usuário posteriormente)
- Os campos marcados com “*” são obrigatórios e o frontend deve verificar se estão preenchidos para permitir que o usuário clique no botão “Criar conta”
- As verificações de nome de usuário, email e cpf (se já constam no banco) ficam melhores se forem realizadas ao preencher o campo e não quando clicar no botão “Criar conta”
- O formulário deve possuir um botão “Criar conta” que salva todos os dados cadastrados no banco de dados
- Por questões de segurança e boas práticas, a senha deve ser salva no banco de dados com criptografia hash (encontra-se funções prontas para isso na internet. Tratar isso no backend). Atentar-se para utilizar a mesma função de hash no cadastro e no login
- Após o cadastro, por questões de segurança, o usuário deve ser direcionado para a tela de login, e não entrar diretamente na plataforma

**Comment by PontesJ** [comment]
Front:

- Padronizar o cabeçalho e o rodapé
