### ISSUE TITLE
RYS12: Eu como comprador, gostaria de poder adicionar vários jogos ao meu carrinho de compras

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#10]
- Nos anúncios da plataforma, devem existir um ícone que permita ao usuário adicionar um anúncio ao seu carrinho de compras
- Deve existir um ícone de carrinho no header da plataforma
- Ao clicar neste ícone, deve ser aberto um pequeno menu com uma lista das coisas que o perfil do usuário adicionou ao carrinho
- A função de remover ítens do carrinho será tratada na RYS14, aqui deve ser possível apenas adicionar
- A função de pagar pelos itens do carrinho será desenvolvida na RYS15
- O carrinho será uma entidade no banco de dados, portanto, a adição ao carrinho não deve acontecer apenas no front, mas no banco também através do back
- E a demonstração dos ítens do carrinho no menu do header deve ser uma pesquisa no banco

**Comment by gabriellaxdantas** [comment]
Carrinho + pagamento - Ok (branch rys12)

**Comment by gabriellaxdantas** [comment]
Adicionado botão "salvar forma de pagamento" e dropdown

**Comment by NicolasMatheusFerreira** [comment]
Nicol
