### ISSUE TITLE
RYS13: Eu como comprador, gostaria de visualizar os detalhes de um anúncio

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#13]
- Deve ser possível clicar em um anúncio da página inicial para ver seus detalhes
- Nos detalhes de um anúncio devem estar: a capa, o título, a sinopse, a descrição, o ano de lançamento, a plataforma e o valor
- Apesar de poder conter o ícone de carrinho, a funcionalidade de adicionar deve ser tratada na RYS12. Caso a RYS12 já esteja concluída, deve ser possível adicionar ao carrinho o anúncio
- Deve ser possível voltar para o catálogo ou página inicial de onde o anúncio foi expandido

**Comment by PontesJ** [comment]
A barra de pesquisa está mudando de tamanho quando entra nos detalhes de um anúncio

![](https://user-images.githubusercontent.com/89613178/239893277-fc95eb54-7cf6-4652-93d9-f4a9519dfd31.png)

![](https://user-images.githubusercontent.com/89613178/239893362-452b0e99-860f-4f57-8f9c-7fc715a4858d.png)
