### ISSUE TITLE
RYS15: Eu como comprador, gostaria de pagar de uma só maneira por todos os itens no meu carrinho

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#15]
- No carrinho de compras deve existir uma maneira de finalizar a compra
- O carrinho deve exibir a soma dos anúncios adicionados (a soma deve ser feita no próprio front)
- Ao clicar em finalizar a compra, o usuário deve ser direcionado para uma página de pagamento
- A página de pagamento deve ser um formulário em que o usuário deverá fornecer: Nome impresso no cartão (string 45 posições no máximo), número do cartão(16 dígitos no máximo), validade(data), cvv(3 dígitos)
- Deve existir um botão "finalizar pagamento", que envia os dados para a rota pertinente do backend
- Após resposta do backend, caso seja positiva, o usuário deve ter o carrinho esvaziado e os jogos devem passar a constar no histórico do usuário
- Caso seja negativa, o front deve exibir o erro retornado pelo back
- O front deve verificar se o número do cartão possui a quantidade correta de números e se o cvv tem apenas 3 dígitos numéricos. A validade deve ser uma data futura
- O front deve exibir uma mensagem de confirmação do pagamento
- Deve existir a opção "Salvar forma de pagamento"
- Deve ser possível utilizar formas de pagamento salvas

**Comment by gabriellaxdantas** [comment]
Carrinho + pagamento - Ok (branch rys12)

**Comment by gabriellaxdantas** [comment]
Adicionado botão "salvar forma de pagamento" e dropdown
