### ISSUE TITLE
RYS18: Eu como comprador, gostaria de visualizar o meu histórico de compras na plataforma

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#16]
- Deve existir uma página onde o usuário pode visualizar os jogos que já adquiriu na plataforma
- Os meios de acesso à página devem ser: pelo menu ao clicar na foto do usuário, opção “Meus Pedidos”
- Para cada jogo que o usuário comprou (o que deve ser consultado no banco), deve ser exibido o item equivalente em uma listagem
- Na listagem devem ser exibidos: o nome do jogo, a capa, o valor, o tipo de mídia e se o jogo já foi ou não entregue.
- Para as mídias virtuais, o usuário deve ser capaz de ver a informação “Forma de acesso” para que consiga acessar a mídia virtual comprada (RYS22)
- Para mídias físicas, caso a mídia física tenha sido comprada a mais de um mês, deve ser setado o valor “sim” para “entregue” no banco de dados
- Para mídias físicas com o valor “nao” em “entregue” no banco de dados, deve aparecer um botão de “confirmar recebimento” e outro “contatar vendedor” e outro “abrir disputa”
- Ao clicar em “contatar vendedor” o contado de celular e email do vendedor devem ser exibidos
- Ao clicar em “abrir disputa”, deve ser exibida uma mensagem informando que a equipe Reyouse entrará em contato com ambas as partes (vendedor e comprador) para analisar o caso (isso será tratado na RYS51)
- Ao clicar em “confirmar recebimento” deve ser exibida uma mensagem de confirmação (se o usuário tem certeza que recebeu a mídia)
- Caso o usuário informe que com certeza recebeu a mídia, o valor de “entregue” deve ser setado para ‘sim’ e os botões devem sumir

**Comment by gabriellaxdantas** [comment]
Função pronta no front-end 
Branch; rys18
Meio de acesso: botão "Meus Pedidos"
