### ISSUE TITLE
RYS22: Eu como comprador, gostaria que jogos do tipo mídia virtual fossem liberados para mim assim que o pagamento fosse confirmado, evitando espera

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#23]
- Após o pagamento confirmado (para entender o pagamento, visualizar a história RYS15), caso o jogo seja do tipo “mídia virtual”, a informação “forma de acesso” salva no banco de dados deve ser exibida para que o comprador consiga acessar seu novo jogo
- Após isso, deve ser dado o prazo de 7 dias para que o comprador informe a Reyouse caso a forma de acesso não esteja correta
- O comprador deve poder confirmar que a forma de acesso funciona através de um botão  (deve existir um botão para “A forma de acesso funcionou” e outro para “A forma de acesso não funcionou”
- Passados 7 dias ou o comprador clicando em “A forma de acesso funcionou”, o pagamento deve ser liberado para o vendedor (RYS28)
- Caso o comprador marque como “A forma de acesso não funcionou”, uma disputa deve ser aberta (RYS51)

**Comment by gabriellaxdantas** [comment]
Requisitos atendidos na branch rys18

- Texto no card para adicionar acesso ao jogo virtual;
- Botão "Acesso funcionou";
- Botão "Acesso não funcionou";
