### ISSUE TITLE
RYS26: Eu como vendedor, gostaria de anunciar um jogo físico na plataforma

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#26]
- Deve existir uma página onde o usuário possa cadastrar um anúncio de um jogo seu para vender.
- Esta página deve, primeiramente, antes de exibir o formulário de cadastro do anúncio, perguntar ao usuário se a mídia a ser vendida é uma mídia física ou virtual
- Caso o tipo de mídia escolhido seja “mídia física”, um formulário de cadastro do anúncio deve ser exibido
- Os campos necessários no formulário de cadastro são: Nome do jogo (para ser pesquisado na API. A API irá retornar uma lista dos jogos com aquele nome buscado e o usuário deve selecionar um dos retornados), Plataforma (O usuário deve selecionar um um dropdown dentre as plataformas aceitas na Reyouse), Descrição (o campo deve existir mas deve ser preenchido automaticamente pelo retorno da API de jogos), sinopse (mesma coisa da descrição), estado de conservação, e preço do jogo
- A API de jogos será tratada na RYS43
- Após preencher todos os dados, o usuário deve clicar em “Publicar Anúncio”
- Ao clicar em “Publicar Anúncio”, uma mensagem perguntando se o usuário tem certeza dos dados do anúncio deve ser exibida
- Se o usuário confirmar que deseja publicar o anúncio, o usuário deve receber uma mensagem de confirmação e o anúncio deve passar a estar disponível para pesquisa na plataforma

**Comment by gabriellaxdantas** [comment]
Função com o front pronto
Branch: rys18
Meio de aceso: botão anunciar -> mídia física

**Comment by PontesJ** [comment]
- Falta a opção de Plataforma

![Image](https://github.com/Reyouse/Geral/assets/79776742/d71e06bf-5d43-4ab7-af23-1a993ff0a55c)

**Comment by gabriellaxdantas** [comment]
Alteração realiza. 


![Image](https://github.com/Reyouse/Geral/assets/102711396/ae8e2e28-016b-4f53-a02d-4bc4854359ed)
