### ISSUE TITLE
RYS27: Eu como vendedor, gostaria de anunciar um jogo virtual na plataforma

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#27]
- Deve existir uma página onde o usuário possa cadastrar um anúncio de um jogo seu para vender.
- Esta página deve, primeiramente, antes de exibir o formulário de cadastro do anúncio, perguntar ao usuário se a mídia a ser vendida é uma mídia física ou virtual
- Caso o tipo de mídia escolhido seja “mídia virtual”, um formulário de cadastro do anúncio deve ser exibido
- Os campos necessários no formulário de cadastro são: Nome do jogo (para ser pesquisado na API. A API irá retornar uma lista dos jogos com aquele nome buscado e o usuário deve selecionar um dos retornados), Plataforma (O usuário deve selecionar um um dropdown dentre as plataformas aceitas na Reyouse), Descrição (o campo deve existir mas deve ser preenchido automaticamente pelo retorno da API de jogos), sinopse (mesma coisa da descrição), forma de acesso (deve ser um campo de digitação livre para que o usuário explique ao comprador, como logar ou resgatar o jogo vendido), e preço do jogo
- A API de jogos será tratada na RYS43
- Após preencher todos os dados, o usuário deve clicar em “Publicar Anúncio”
- Ao clicar em “Publicar Anúncio”, uma mensagem perguntando se o usuário tem certeza dos dados do anúncio deve ser exibida
- Se o usuário confirmar que deseja publicar o anúncio, o usuário deve receber uma mensagem de confirmação e o anúncio deve passar a estar disponível para pesquisa na plataforma

**Comment by PontesJ** [comment]
- Falta a opção de Plataforma

![Image](https://github.com/Reyouse/Geral/assets/79776742/5cd47b1a-bdac-4e75-9b6f-dc88d23b9643)

**Comment by gabriellaxdantas** [comment]
Alteração realizada. 

![Image](https://github.com/Reyouse/Geral/assets/102711396/d65508f7-22bd-4daf-9fda-e6d0b1b25b65)
