### ISSUE TITLE
RYS43: Eu como vendedor, gostaria que a plataforma completasse dados do anúncio do jogo para mim (como descrição, sinopse)

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#29]
- Esses dados serão buscados pelo backend na API do IGDB
- No front, o campo “nome do jogo” no cadastro de anúncio, precisa ser um campo de pesquisa, onde, a partir da rota do backend, retorna os jogos com o nome pesquisado 
- O usuário então deve ver uma lista com as capas e nomes dos jogos retornados pela api para selecionar um
- Após selecionar um jogo dentre os pesquisados, os campos “nome do jogo”, “sinopse”, “descrição”, “capa”, “banner”, devem ser preenchidos automaticamente no front

**Comment by pedrosiqueirapb** [comment]
o nome dos arquivos da tela da lista de jogos retornada pela API são: anuncioFinal.html   anuncioFinal.css e anuncioFinal.js

Ao clicar em "confirmar" no pop-up, o usuário ele é redirecionado para tela de informações do usuário, no qual ele pode visualizar o anúncio na parte de "Meus anúncios"
