### ISSUE TITLE
RYS40: Eu como vendedor, gostaria de poder alterar o anúncio de um jogo que eu anunciei

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#48]
- Deve existir na plataforma, um histórico de anúncios criados pelo usuário
- No histórico, deve ser possível que o usuário escolha um dos anúncios criados por ele para que ele edite as informações do anúncio 
- Deve ser possível editar apenas o preço, os dados de acesso (se digital),  o estado de conservação (se física), o tipo de mídia e a plataforma
- Não deve ser possível editar informações do jogo, já que é retorno da API
- Não deve ser possível trocar o jogo de um anúncio, já que o jogo é que define o anúncio. Caso o usuário deseje anunciar outro jogo, deve criar outro anúncio

**Comment by gabriellaxdantas** [comment]
Funcionalidade adicionada na branch rys18.
Existe uma criada para edição de jogos digitais e outra para jogos físicos, obedecendo os requisitos de cada uma delas.

Meus anúncio > caneta > Editar Anuncio



![Image](https://github.com/Reyouse/Geral/assets/102711396/b981bd8b-e4b0-48ae-8a2f-ea4f46760536)
