### ISSUE TITLE
RYS41: Eu como vendedor, gostaria de poder excluir um anúncio que criei

### ISSUE THREAD

**Issue by caiovitfernandes** [Reyouse/Geral#49]
- Deve existir na plataforma, um histórico de anúncios criados pelo usuário
- No histórico, deve ser possível que o usuário escolha um dos anúncios criados por ele para que ele exclua o anúncio
- A exclusão deve ocorrer também no banco de dados
- Antes de excluir de fato, deve existir uma mensagem de confirmação para que o usuário confirme que deseja de fato excluir o anúncio
- Os anúncios já vendidos não devem ser excluídos do histórico, mas apenas marcados como “Vendido”

**Comment by gabriellaxdantas** [comment]
Front criado na branch rys18
Meus Anuncio > lixeira
